[package]
name = "pfsense-dashboard"
version = "0.1.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"

[dependencies]
backtrace = "0.3"
dirs = "2"
roxmltree = "0.11"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.8"
ssh2 = "0.8"
